replicaCount: 1

image:
  repository: gleb8/users-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  internalPort: 8080
  externalPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

appName: "users"

# Reference to your shared secret
secrets:
  # This should match the name in your secrets.yaml
  sharedSecretName: app-secrets

# Environment variables that are NOT secrets
env:
  springProfilesActive: "docker"
  serverPort: 8080
  springDatasourceUrl: "jdbc:postgresql://postgres-users-service:5432/loans-users"
  # springDatasourceUsername: "loansusers"
  # springDatasourcePassword: "loansusers_password"
  eurekaClientServiceUrlDefaultZone: "http://eureka-server-service:8761/eureka/"
  eurekaInstanceHostname: "users-service"
