services:
  postgres_db_users:
    image: postgres:17-alpine
    container_name: loans-users-postgres
    networks:
      - localprom
    environment:
      POSTGRES_DB: loans-users
      POSTGRES_USER: loansusers
      POSTGRES_PASSWORD: loansusers_password
    ports:
      - "5440:5432"
    volumes:
      - loans-users-postgres-data:/var/lib/postgresql/data

  postgres-exporter-users:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter-users
    networks:
      - localprom
    environment:
      DATA_SOURCE_NAME: "postgresql://loansusers:loansusers_password@postgres_db_users:5432/loans-users?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres_db_users

  postgres_db_loans:
    image: postgres:17-alpine
    container_name: loans-loans-postgres
    networks:
      - localprom
    environment:
      POSTGRES_DB: loans-loans
      POSTGRES_USER: loansusers
      POSTGRES_PASSWORD: loansusers_password
    ports:
      - "5441:5432"
    volumes:
      - loans-loan-postgres-data:/var/lib/postgresql/data

  postgres-exporter-loans:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter-loans
    networks:
      - localprom
    environment:
      DATA_SOURCE_NAME: "postgresql://loansusers:loansusers_password@postgres_db_loans:5432/loans-loans?sslmode=disable"
    ports:
      - "9188:9187"
    depends_on:
      - postgres_db_loans

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    volumes:
      - "./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml"
      - "./monitoring/rules:/etc/prometheus/rules"
      - "prometheus-data:/prometheus"
    networks:
      - localprom
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - localprom
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter
    networks:
      - localprom
    ports:
      - 9100:9100

  alert-manager:
    image: prom/alertmanager
    volumes:
      - "./monitoring/alertmanager.yaml:/etc/alertmanager/alertmanager.yml"
      - "alertmanager-data:/data"
    networks:
      - localprom
    ports:
      - 9093:9093

  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: blackbox-exporter
    networks:
      - localprom
    volumes:
      - "./monitoring/blackbox.yaml:/config/blackbox_exporter/config.yml"
    ports:
      - "9115:9115"

  
  # Keycloak Database
  postgres_db_keycloak:
    image: postgres:17-alpine
    container_name: keycloak-postgres
    networks:
      - localprom
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
    ports:
      - "5442:5432"
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data

  keycloak:
    image: keycloak/keycloak:latest
    container_name: keycloak
    networks:
      - localprom
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_db_keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_PROXY_ADDRESS_FORWARDING: true
    ports:
      - "7001:8080"
    depends_on:
      - postgres_db_keycloak
    command: start-dev

  mailhog:
    image: jcalonso/mailhog:latest
    container_name: mailhog
    networks:
      - localprom
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port

volumes:
  loans-users-postgres-data:
  loans-loan-postgres-data:
  prometheus-data:
  alertmanager-data:
  grafana-data:
  keycloak-postgres-data:

networks:
  localprom:
    driver: bridge
