replicaCount: 1

image:
  repository: gleb8/gateway-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  internalPort: 8090
  externalPort: 8090

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Reference to your shared secret
secrets:
  # This should match the name in your secrets.yaml
  sharedSecretName: app-secrets

# Environment variables that are NOT secrets
env:
  springProfilesActive: "docker"
  springApplicationName: "gateway"
  serverPort: 8090
  eurekaClientServiceUrlDefaultZone: "http://umbrella-eureka-server-service:8761/eureka/"
  eurekaInstanceHostname: "umbrella-gateway-service-service"

logging:
  level:
    root: "INFO"
    eureka: "DEBUG"
    web: "DEBUG"
    hibernate: "INFO"
    hibernateSQL: "DEBUG"
    gateway: "TRACE"
    application: "DEBUG"

jpa:
  showSQL: true
  formatSQL: true

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    # Global circuit breaker configuration
    configs:
      default:
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        failureRateThreshold: 60
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 3s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true

  # Retry configuration
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s

  # Time limiter configuration
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
        cancelRunningFuture: true

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
