spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/loans-users
    username: loansusers
    password: loansusers_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true

  application:
    name: users

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  metrics:
    tags:
      application: users
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  ratelimiter:
    configs:
      default:
        timeout-duration: 1000 # if no tickets are available, it will wait when new tickets will be available, if not, it will throw an error 
        limit-refresh-period: 10000 # period time, then it restarts
        limit-for-period: 20 # amount of tickets ( requests ) per period
      
