apiVersion: v2
name: postgres-users
description: PostgreSQL database for users microservice
version: 0.1.0
appVersion: "17.6.0"

dependencies:
- name: postgresql
  version: "16.7.26"
  repository: "https://charts.bitnami.com/bitnami"
