global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alert-manager:9093

rule_files:
- "rules/users_rules.yaml"
- "rules/other_rules.yaml"

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - prometheus:9090

- job_name: grafana
  static_configs:
  - targets:
    - grafana:3000

- job_name: eureka-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets:
    - host.docker.internal:8761

- job_name: users-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets:
    - host.docker.internal:8081

- job_name: loans-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets:
    - host.docker.internal:8082

- job_name: gateway-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets:
    - host.docker.internal:8090

- job_name: node-exporter
  static_configs:
  - targets:
    - node-exporter:9100

- job_name: blackbox-exporter
  static_configs:
  - targets:
    - blackbox-exporter:9115

- job_name: postgres-exporter-users
  static_configs:
  - targets:
    - postgres-exporter-users:9187

- job_name: postgres-exporter-loans
  static_configs:
  - targets:
    - postgres-exporter-loans:9187

- job_name: 'blackbox-exporter-routes'
  metrics_path: /probe
  params:
    module: [ http_2xx ]
  static_configs:
  - targets:
    - 'http://host.docker.internal:8090/actuator/health'
    - 'http://host.docker.internal:8090/users/actuator/health'
    - 'http://host.docker.internal:8090/loans/actuator/health'
  # This relabeling is the key part that makes the blackbox exporter work.
  relabel_configs:
  # 1. Takes the target URL and saves it as a parameter for the exporter.
  - source_labels: [ __address__ ]
    target_label: __param_target
  # 2. Makes the target URL the human-readable 'instance' label.
  - source_labels: [ __param_target ]
    target_label: instance
  # 3. Changes the actual scrape target to the blackbox exporter's address.
  - target_label: __address__
    replacement: blackbox-exporter:9115
