global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alert-manager:9093

rule_files:
- "rules/users_rules.yaml"
- "rules/other_rules.yaml"

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - prometheus:9090

- job_name: eureka-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets:
    - host.docker.internal:8761

- job_name: users-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets:
    - host.docker.internal:8081

- job_name: loans-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets:
    - host.docker.internal:8082

- job_name: gateway-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets:
    - host.docker.internal:8090

- job_name: node-exporter
  static_configs:
  - targets:
    - node-exporter:9100
