replicaCount: 1

image:
  repository: gleb8/loans-service
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  internalPort: 8080
  externalPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

appName: "loans"

# Reference to your shared secret
secrets:
  # This should match the name in your secrets.yaml
  sharedSecretName: app-secrets

# Environment variables that are NOT secrets
env:
  springProfilesActive: "docker"
  serverPort: 8080
  springDatasourceUrl: "jdbc:postgresql://postgres-loans-service:5432/loans-loans"
  eurekaClientServiceUrlDefaultZone: "http://eureka-server-service:8761/eureka/"
  eurekaInstanceHostname: "loans-service"
