server:
  port: 8086 

spring:
  application:
    name: auth

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL for service discovery
  instance:
    hostname: localhost  # Eureka instance hostname

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all actuator endpoints
  endpoint:
    health:
      show-details: "always"  # Show detailed health info
  metrics:
    tags:
      application: auth  # Add application tag to metrics

jwt:
  secret: "OT39JZ2rZQ2D/EbnJu9trUMV3gRptzA1Dk3wVqEn6VHnIAy4hs3Ml/Aoh0ckROWCH/oydgsDzFonYtlJmDfnY98JRGSWw04S+f6dhIRv+CiLTRtsFPxrYFLCjBDZZVOkTA2QuFyuHMy+ZGtEagSmF6xQm0DTBqb8shoqfsj+9P"
  expiration: 3600000 # 1 hour

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.discovery: DEBUG
