apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "auth-service.fullname" . }}
  ports:
    - name: internal
      port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.internalPort }}
    - name: external
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
