replicaCount: 1

image:
  repository: gleb8/auth-service
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  internalPort: 8080
  externalPort: 8086

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Reference to your shared secret
secrets:
  # This should match the name in your secrets.yaml
  sharedSecretName: app-secrets

# Environment variables that are NOT secrets
env:
  springProfilesActive: "docker"
  springApplicationName: "auth"
  serverPort: 8080
  eurekaClientServiceUrlDefaultZone: "http://umbrella-eureka-server-service:8761/eureka/"
  instanceHostname: "umbrella-auth-service"
