apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-service.fullname" . }}-deployment
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "auth-service.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "auth-service.fullname" . }}
    spec:
      containers:
        - name: auth-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.serverPort | quote }}
            - name: SPRING_APPLICATION_NAME
              value: {{ .Values.env.springApplicationName | quote }}
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: {{ .Values.env.eurekaClientServiceUrlDefaultZone | quote }}
            - name: EUREKA_INSTANCE_HOSTNAME
              value: {{ .Values.env.instanceHostname | quote }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.sharedSecretName }}
                  key: JWT_SECRET
            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.sharedSecretName }}
                  key: JWT_EXPIRATION
