global:
  readReplicas:
    replicaCount: 1

  postgresql:
    fullnameOverride: "umbrella-postgres-loans"

    auth:
      database: "loans-loans"
      postgresPassword: "loansusers_password"
      username: "loansusers"
      password: "loansusers_password"

    primary:
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      persistence:
        enabled: true
        size: 8Gi
        storageClass: ""

    service:
      type: ClusterIP
      ports:
        postgresql: 5432
